In [7]:
#1D Array
import numpy as np
x = np.arange(2,6).reshape(4)
print("1D Array:")
print(x)
#2D Array
y = np.arange(2,10).reshape(2,4)
print('2D Array:')
print(y)

#3D Array
z = np.arange(24).reshape(4,3,2)
print("3D Array:")
z


1D Array:
[2 3 4 5]
2D Array:
[[2 3 4 5]
 [6 7 8 9]]
3D Array:


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [8]:
"""
1. Write a NumPy program to print the NumPy version in your system
"""
import numpy as np
print(np.__version__)

1.20.3


In [9]:
"""
2. Write a NumPy program to convert a list ofnumeric value into a one-dimensional NumPy array 
"""
import numpy as np
l = [12.23,13.32,100,36.32]
print('Original List:',l)
a = np.array(l)
print('One-dimensional NumPy array:',a)

Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array: [ 12.23  13.32 100.    36.32]


In [10]:
"""
3.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
"""
import numpy as np
x = np.arange(2,11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [13]:
"""
4. Write a NumPy program to create a null vectorof size 10 and update sixth value to 11
"""
import numpy as np
x = np.zeros(10)
print(x)
print('Update sixth value to 11')
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [18]:
"""
5. Write a NumPy program to create an array with values ranging from 12 to 38
"""
x = np.arange(12,38)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [23]:
"""
6. Write a NumPy program to reverse an array (first element becomes last).
"""
x = np.arange(12,38)
print('Orignal:')
print(x)
print('Reverse:')
print(x[::-1])

Orignal:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [24]:
"""
7. Write a NumPy program to convert an array to a float type.
"""
import numpy as np
a = [1,2,3,4]
print('Original Array')
print(a)
x = np.asfarray(a)
print('Array converted to a float type:')
print(x)

Original Array
[1, 2, 3, 4]
Array converted to a float type:
[1. 2. 3. 4.]


In [25]:
"""
8. Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 
"""
import numpy as np
x = np.ones((5,5))
print('Original Array:')
print(x)
print('1 on the border and 0 inside in the array')
x[1:-1,1:-1] = 0
print(x)

Original Array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [26]:
"""
9. Write a NumPy program to add a border (filled with 0's) around an existing array. 
"""
import numpy as np
x = np.ones((3,3))
print('Original Array:')
print(x)
print('0 on the border and 1 inside in the array')
x =np.pad(x,pad_width = 1, mode = 'constant', constant_values = 0)
print(x)

Original Array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [32]:
"""
10. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.
"""
import numpy as np
x = np.ones((3,3))
print('Checkboard Pattern:')
x = np.zeros((8,8),dtype = int)
x[1::2,::2] = 8
x[::2,1::2] = 8
print(x)

Checkboard Pattern:
[[0 8 0 8 0 8 0 8]
 [8 0 8 0 8 0 8 0]
 [0 8 0 8 0 8 0 8]
 [8 0 8 0 8 0 8 0]
 [0 8 0 8 0 8 0 8]
 [8 0 8 0 8 0 8 0]
 [0 8 0 8 0 8 0 8]
 [8 0 8 0 8 0 8 0]]


In [29]:
"""
11. Write a NumPy program to convert a list and tuple into arrays.
"""
import numpy as np
my_list = [1,2,3,4,5,6,7,8]
print('List to array:')
print(np.asarray(my_list))
my_tuple = ([8,4,6],[1,2,3])
print('Tuple to array: ')
print(np.asarray(my_tuple))


List to array:
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


In [30]:
"""
12. Write a NumPy program to append values to the end of an array. 
"""
import numpy as np
x = [10,20,30]
print('Original Array:')
print(x)
x = np.append(x,[[40,50,60],[70,80,90]])
print('After append values to the end of the Array:')
print(x)

Original Array:
[10, 20, 30]
After append values to the end of the Array:
[10 20 30 40 50 60 70 80 90]


In [36]:
"""
13. Write a NumPy program to create an empty and a full array.
"""
import numpy as np
# Create an empty array
x = np.empty((3,4))
print(x)
# Create a full array
y = np.full((3,3),5)
print(y)

[[1.36678159e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 7.61215646e-042 2.72528669e-056 2.62141380e+180]
 [1.48542101e-076 4.43215775e+175 4.08686332e-037 2.87924484e+180]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [37]:
"""
14. Write a NumPy program to convert the values of Centigrade degrees 
into Fahrenheit degrees. Centigrade values are stored into a NumPy array.  
"""
import numpy as np
fvalues = [0,12,45.21,34,99.91]
F = np.array(fvalues)
print('Values in Fahrenheit degrees:')
print(F)
print('Values in Centigrade degrees:')
print(5*F/9 - 5*32/9)


Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


In [39]:
"""
15. Write a NumPy program to find the real and imaginary parts of an array of complex numbers.
"""
import numpy as np
x = np.sqrt([1+0j])
y = np.sqrt([0+1j])
print('Original array:x',x)
print('Original array:y',y)
print('Real part of the array:')
print(x.real)
print(y.real)
print('Imaginary part of the array')
print(x.imag)
print(y.imag)


Original array:x [1.+0.j]
Original array:y [0.70710678+0.70710678j]
Real part of the array:
[1.]
[0.70710678]
Imaginary part of the array
[0.]
[0.70710678]


In [40]:
"""
16.Write a NumPy program to find the number of elements of an array, 
length of one array element in bytes and total bytes consumed by the elements
"""
import numpy as np
x = np.array([1,2,3], dtype = np.float64)
print('Size of the array:',x.size)
print('Length of one array element in bytes: ',x.itemsize)
print('Total bytes consumed by the elements of the array: ',x.nbytes)

Size of the array: 3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


In [42]:
"""
17. Write a NumPy program to test whether each element of 
a 1-D array is also present in a second array 
"""
import numpy as np
array1 = np.array([0,10,20,40,60])
print('Array1:',array1)
array2 = [0,40]
print('Array2:',array2)
print('Compare each element of array1 and array2')
print(np.in1d(array1,array2))

Array1: [ 0 10 20 40 60]
Array2: [0, 40]
Compare each element of array1 and array2
[ True False False  True False]


In [44]:
"""
18. Write a NumPy program to find common values between two arrays
"""
import numpy as np
array1 = np.array([0,10,20,40,60])
print('Array1:',array1)
array2 = [10,30,40]
print('Array2:',array2)
print('Common values between two arrays:')
print(np.intersect1d(array1,array2))

Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]
Common values between two arrays:
[10 40]


In [46]:
"""
19. Write a NumPy program to get the unique elements of an array. 
"""
import numpy as np
x = np.array([10,10,20,20,30,30])
print('Original Array:')
print(x)
print('Unique elements of the above array:')
print(np.unique(x))
x = np.array([[1,1],[2,3]])
print('Original Array:')
print(x)
print("Unique elements of the above array:")
print(np.unique(x))

Original Array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original Array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


In [48]:
"""
20. Write a NumPy program to find the set difference of two arrays. 
The set difference will return the sorted, unique values in array1 that are not in array2
"""
import numpy as np
array1 = np.array([0,10,20,40,60,80])
print('Array1:',array1)
array2 = [10,30,40,50,70]
print('Array2:', array2)
print("Unique values in array1 that are not in array2:")
print(np.setdiff1d(array1,array2))

Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70]
Unique values in array1 that are not in array2:
[ 0 20 60 80]


In [49]:
"""
21. Write a NumPy program to find the set exclusive-or of two arrays. 
Set exclusive-or will return the sorted, unique values that are in only one (not both) of 
the input arrays
"""
import numpy as np
array1 = np.array([0,10,20,40,60,80])
print('Array1: ',array1)
array2 = [10,30,40,50,70]
print('Array2: ',array2)
print('Unique values that are in only one (not both) of the input arrays:')
print(np.setxor1d(array1,array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


In [50]:
"""
22. Write a NumPy program to find the union of two arrays.
Union will return the unique, sorted array of values that are in either of the two input arrays
"""
import numpy as np
array1 = np.array([0,10,20,40,60,80])
print('Array1:',array1)
array = [10,30,40,50,70]
print('Array2 :',array2)
print('Unique sorted array of the values that are in either of the two input arrays:')
print(np.union1d(array1,array2))

Array1: [ 0 10 20 40 60 80]
Array2 : [10, 30, 40, 50, 70]
Unique sorted array of the values that are in either of the two input arrays:
[ 0 10 20 30 40 50 60 70 80]


In [52]:
"""
23. Write a NumPy program to test whether all elements in an array evaluate to True
"""
import numpy as np
print(np.all([[True,False],[True,True]]))
print(np.all([[True,True],[True,True]]))
print(np.all([10,20,0,-50]))
print(np.all([10,20,-50]))

False
True
False
True


In [53]:
"""
25. Write a NumPy program to construct an array by repeating.
"""
import numpy as np
a = [1,2,3,4]
print('Original array')
print(a)
print('Repeating 2 times')
x = np.tile(a,2)
print(x)
print('Repeating 3 times')
x = np.tile(a,3)
print(x)

Original array
[1, 2, 3, 4]
Repeating 2 times
[1 2 3 4 1 2 3 4]
Repeating 3 times
[1 2 3 4 1 2 3 4 1 2 3 4]


In [54]:
"""
26. Write a NumPy program to repeat elements of an array.
"""
import numpy as np
x = np.repeat(3,4)
print(x)
x = np.array([[1,2],[3,4]])
print(np.repeat(x,2))

[3 3 3 3]
[1 1 2 2 3 3 4 4]


In [56]:
"""
27. Write a NumPy program to find the indices of the maximum and minimum values
along the given axis of an array.
"""
import numpy as np
x = np.array([1,2,3,4,5,6,9])
print('Original Array:',x)
print('Maximum Values:',np.argmax(x))
print('Minimum Values:',np.argmin(x))

Original Array: [1 2 3 4 5 6 9]
Maximum Values: 6
Minimum Values: 0


In [57]:
"""
28. Write a NumPy program compare two given arrays 
"""
import numpy as np
a = np.array([1,2])
b = np.array([4,5])
print('Array a:',a)
print('Array b:',b)
print('a>b')
print(np.greater(a,b))
print('a>=b')
print(np.greater_equal(a,b))
print('a<b')
print(np.less(a,b))
print('a<=b')
print(np.less_equal(a,b))

Array a: [1 2]
Array b: [4 5]
a>b
[False False]
a>=b
[False False]
a<b
[ True  True]
a<=b
[ True  True]


In [58]:
"""
29. Write a NumPy program to sort an along the first, last axis of an array. 
"""
import numpy as np
a = np.array([[4,6],[2,1]])
print('Original Array:')
print(a)
print('Sort along the first axis:')
x = np.sort(a,axis=0)
print(x)
print('Sort along the last axis:')
y = np.sort(x,axis = 1)
print(y)

Original Array:
[[4 6]
 [2 1]]
Sort along the first axis:
[[2 1]
 [4 6]]
Sort along the last axis:
[[1 2]
 [4 6]]


In [60]:
"""
30. Write a NumPy program to sort pairs of first name and last name return their indices. 
(first by last name, then by first name). 
"""
import numpy as np
first_names = ('Margery','Betsey','Shellbey','Lanell','Genesis')
last_names = ('Woolum','Battle','Plotner','Brien','stahl')
x = np.lexsort((first_names,last_names))
print(x)

[1 3 2 0 4]
